bbs/urls.py
from django.urls import path, include
from . import views as bbs_views

urlpatterns = [
    path('bbs/<bbs_type>/list', bbs_views.PostListView.as_view(), name='board-list'),
    path('bbs/<bbs_type>/add', bbs_views.PostCreateView.as_view(), name='board-add'),
    path('bbs/<bbs_type>/<int:pk>/', bbs_views.PostDetailView.as_view(), name='board-detail'),
    path('bbs/<bbs_type>/<int:pk>/delete', bbs_views.PostDeleteView.as_view(), name='board-delete'),
    path('bbs/<bbs_type>/<int:pk>/update', bbs_views.PostUpdateView.as_view(), name='board-update'),
]

pet/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views as pet_views

urlpatterns = [
    path('<int:userid>/pets', pet_views.PetListView.as_view(), name='pet-list'),
    path('<int:userid>/pet/add', pet_views.PetCreateView.as_view(), name='pet-add'),
    path('<int:userid>/pet/<int:pk>', pet_views.PetDetailView.as_view(), name='pet-detail'),
    path('<int:userid>/pet/<int:pk>/update', pet_views.PetUpdateView.as_view(), name='pet-update'),
    path('<int:userid>/pet/<int:pk>/delete', pet_views.PetDeleteView.as_view(), name='pet-delete'),
    path('<int:userid>/pet/<int:petid>/care/add', pet_views.CareCreateView.as_view(), name='care-add'),
    path('<int:userid>/pet/<int:petid>/care/<int:pk>/delete', pet_views.CareDeleteView.as_view(), name='care-delete'),
    path('ajax/ajax-search-species', pet_views.SpeciesSearchTemplateView.as_view(), name='ajax-search-species'),
]

pet/models.py
from django.db import models
from django.conf import settings
from dict.models import Dictionary, AnimalDictionary
from django.utils import timezone
from django.urls import reverse
from django.utils.formats import localize
from taggit.managers import TaggableManager
import reptopia

class Pet(models.Model):
    species = models.ForeignKey(AnimalDictionary, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    gender = models.ForeignKey(
        Dictionary,
        related_name='gender',
        on_delete=models.CASCADE,
        limit_choices_to={'category': reptopia._GENDER_},
    )
    bod = models.DateField(blank=True, null=True)
    image = models.ImageField(upload_to='pet/%Y/%m/%d', blank=True, null=True)
    desc = models.TextField(blank=True)

    created_date = models.DateTimeField(default=timezone.now)

    tags = TaggableManager()

    def __str__(self):
        return '[' + self.species.common_name_kor + ']' + self.name;

    def get_absolute_url(self):
        return reverse('pet-detail', kwargs={'userid': self.owner.pk, 'pk': self.pk})

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.tags.clear()
        super(Pet, self).delete(*args, **kwargs)

    def get_model_name(self):
        return Pet.__name__


class Feeding(models.Model):
    eat_type = models.ForeignKey(
        Dictionary,
        related_name='eat_type',
        on_delete=models.CASCADE,
        default=21
    )
    prey_type = models.ForeignKey(
        Dictionary,
        related_name='prey_type',
        on_delete=models.CASCADE,
    )
    prey_size = models.ForeignKey(
        Dictionary,
        related_name='prey_size',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    prey_weight = models.IntegerField(blank=True, null=True)
    prey_quantity = models.IntegerField(default=1)


class Care(models.Model):
    date = models.DateField(default=timezone.now, blank=False)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    type = models.ForeignKey(
        Dictionary,
        related_name='care_type',
        on_delete=models.CASCADE,
        limit_choices_to={'category': reptopia._CARE_},
    )
    weight = models.IntegerField(null=True)
    feeding = models.ForeignKey(
        Feeding,
        on_delete=models.CASCADE,
        null=True
    )
    image = models.ImageField(upload_to='care/%Y/%m/%d', blank=True, null=True)
    desc = models.TextField(blank=True)
    created_datetime = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.pet.name + " : " + localize(self.date) + " : " + self.type.item

    def delete(self, *args, **kwargs):
        self.image.delete()
        if self.feeding:
            self.feeding.delete()
        super(Care, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pet-detail', kwargs={'userid': self.pet.owner.pk, 'pk': self.pet.pk})

pet/forms.py
from django import forms
from django.forms import ModelForm, HiddenInput
from django.shortcuts import get_object_or_404
from dict.models import Dictionary, AnimalDictionary
from .models import Pet, Care, Feeding
import reptopia
import logging

logger = logging.getLogger('reptopia.log')


class PetCreateForm(ModelForm):
    class Meta:
        model = Pet
        fields = ('species', 'name', 'gender', 'bod', 'desc', 'image')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['species'].widget.attrs.update({'style': 'visibility:hidden; width:0px; height:0px;'})
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})
        self.fields['bod'].widget.attrs.update({'class': 'form-control', 'readonly': 'true'})
        self.fields['desc'].widget.attrs.update({'class': 'form-control'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})

        self.fields['species'].label = "개체종류"
        self.fields['name'].label = "이름"
        self.fields['gender'].label = "성별"
        self.fields['bod'].label = "부화일자"
        self.fields['image'].label = "대표사진"
        self.fields['desc'].label = "설명"

        self.fields['species'].help_text = '개체의 종류를 두글자 이상 입력하고 자동완성 기능을 이용해 선택해주세요.'

class CareCreateForm(ModelForm):
    class Meta:
        model = Care
        fields = ('date', 'pet', 'type', 'weight', 'desc', 'image')

    weight = forms.IntegerField(required=False)
    eat_type = forms.ModelChoiceField(queryset=Dictionary.objects.filter(category='PT00000000'), required=False)
    prey_type = forms.ModelChoiceField(queryset=Dictionary.objects.all(), required=False)
    prey_size = forms.ModelChoiceField(queryset=Dictionary.objects.all(), required=False)
    prey_weight = forms.IntegerField(required=False)
    prey_quantity = forms.IntegerField(required=False)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].widget.attrs.update({'class': 'form-control', 'readonly': 'true'})
        self.fields['pet'].widget.attrs.update({'class': 'form-control'})
        self.fields['type'].widget.attrs.update({'class': 'form-control'})
        self.fields['weight'].widget.attrs.update({'class': 'form-control', 'placeholder': '개체의 체중을 그램(gram) 단위로 숫자만 입력해주세요.'})
        self.fields['desc'].widget.attrs.update({'class': 'form-control'})
        self.fields['image'].widget.attrs.update({'class': 'form-control'})

        self.fields['eat_type'].widget.attrs.update({'class': 'form-control'})
        self.fields['prey_type'].widget.attrs.update({'class': 'form-control', 'disabled': True})
        self.fields['prey_size'].widget.attrs.update({'class': 'form-control', 'disabled': True})
        self.fields['prey_weight'].widget.attrs.update({'class': 'form-control', 'placeholder': '그램(gram) 단위로 정수만 입력해주세요.'})
        self.fields['prey_quantity'].widget.attrs.update({'class': 'form-control', 'placeholder': '먹이 수량을 정수로 입력해주세요.'})


        self.fields['date'].label = "사육일자"
        self.fields['type'].label = "일지유형"
        self.fields['weight'].label = "체중"
        self.fields['desc'].label = "기타"
        self.fields['image'].label = "사육사진"

        self.fields['eat_type'].label = "먹이유형"

    def clean(self):
        cleaned_data = super(CareCreateForm, self).clean()

        type = cleaned_data.get("type")
        if type is None:
            self.add_error('type', "사육일지 유형은 필수 입력 항목입니다.")
            raise forms.ValidationError("사육일지에 필수 항목이 누락되었습니다.")

        weight = cleaned_data.get("weight")
        eat_type = cleaned_data.get("eat_type")
        prey_type = cleaned_data.get("prey_type")
        prey_size = cleaned_data.get("prey_size")
        prey_weight = cleaned_data.get("prey_weight")
        prey_quantity = cleaned_data.get("prey_quantity")


        if type.item == reptopia._WEIGHT_ and weight is None:
            self.add_error('weight', "체중은 필수 입력 항목입니다.")
            raise forms.ValidationError("체중 사육일지에 필수 항목이 누락되었습니다.")
        elif type.item == reptopia._FEEDING_:
            if eat_type is None:
                self.add_error('eat_type', "먹이 분류가 선택되지 않았습니다.")
                raise forms.ValidationError("먹이주기 사육일지에 필수 항목이 누락되었습니다.")
            if prey_type is None:
                self.add_error('eat_type', "먹이 유형이 선택되지 않았습니다.")
                raise forms.ValidationError("먹이주기 사육일지에 필수 항목이 누락되었습니다.")
            if prey_quantity is None:
                self.add_error('eat_type', "먹이 수량은 필수 입력 항목입니다.")
                raise forms.ValidationError("먹이주기 사육일지에 필수 항목이 누락되었습니다.")

        return cleaned_data

pet/views.py
from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.db import transaction
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from account.models import Account
from dict.models import AnimalDictionary, Dictionary
from .models import Pet, Care, Feeding
from .forms import PetCreateForm, CareCreateForm
import reptopia
import logging
import json

logger = logging.getLogger('reptopia.log')

class PetListView(LoginRequiredMixin, ListView):
    login_url = settings.LOGIN_URL
    model = Pet
    template_name = 'pet/pet_list.html.j2'
    context_object_name = 'pet_list'
    paginate_by = reptopia._PAGE_CNT_ 

    def get_queryset(self):
        current_user = get_object_or_404(Account, pk=self.kwargs['userid'])
        query_set = Pet.objects.filter(owner=current_user) # 사육기간 필터입력추가

        if 'speciesid' in self.request.GET:
            species = get_object_or_404(AnimalDictionary, pk=self.request.GET['speciesid'])
            query_set = query_set.filter(species=species)

        query_set = query_set.order_by('-created_date')
        return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        owner = get_object_or_404(Account, pk=self.kwargs['userid'])
        have_species_list = Pet.objects.values_list('species', flat=True).distinct()
        species_list = AnimalDictionary.objects.filter(id__in=have_species_list)

        context['owner'] = owner
        context['species_list'] = species_list

        return context

class PetCreateView(LoginRequiredMixin, CreateView):
    login_url = settings.LOGIN_URL
    model = Pet
    form_class = PetCreateForm
    template_name = 'pet/pet_form.html.j2'

    @transaction.atomic
    def form_valid(self, form):
        if form.is_valid():
            form.instance.owner = self.request.user
            pet = form.save(commit=False)
            pet.save()
            form.instance.tags.add(pet.species.common_name_kor)
            form.save_m2m()
            return redirect(pet)
        else:
            return super().form_invalid(form)

class PetUpdateView(LoginRequiredMixin, UpdateView):
    login_url = settings.LOGIN_URL
    model = Pet
    form_class = PetCreateForm
    template_name = 'pet/pet_form.html.j2'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pet = get_object_or_404(Pet, pk=self.kwargs['pk'])
        context['pet'] = pet

        return context

    @transaction.atomic
    def form_valid(self, form):
        if form.is_valid():
            form.instance.owner = self.request.user
            pet = form.save(commit=False)

            current_pet = get_object_or_404(Pet, pk=self.kwargs['pk'])
            form_pet = form.save(commit=False)
            if current_pet.id == form_pet.id and current_pet.image != form_pet.image:
                current_pet.image.delete()

            pet.save()
            form.instance.tags.set(pet.species.common_name_kor, clear=True)
            form.save_m2m()
            return redirect(pet)
        else:
            return super().form_invalid(form)


class PetDeleteView(LoginRequiredMixin, DeleteView):
    login_url = settings.LOGIN_URL
    model = Pet 

    def get_success_url(self):
        owner = self.object.owner
        return reverse_lazy('pet-list', kwargs={'userid': owner.id})


class PetDetailView(DetailView):
    model = Pet
    template_name = 'pet/pet_detail.html.j2'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        care_type_list = Dictionary.objects.filter(category=reptopia._CARE_)
        context['care_type_list'] = care_type_list

        pet = get_object_or_404(Pet, pk=self.kwargs['pk']);
        care_list_all = Care.objects.filter(pet=pet).order_by('-date', '-created_datetime')

        if 'care_type' in self.request.GET:
            care_list_all = care_list_all.filter(type_id=self.request.GET['care_type'])

        paginator = Paginator(care_list_all, reptopia._PAGE_CNT_)
        page = self.request.GET.get('page')
        try:
            care_list = paginator.page(page)
        except PageNotAnInteger:
            care_list = paginator.page(reptopia._FIRST_PAGE_)
        except EmptyPage:
            care_list = paginator.page(paginator.num_pages)
        context['care_list'] = care_list

        dict_weight = get_object_or_404(Dictionary, item=reptopia._WEIGHT_)
        weight_list = Care.objects.filter(pet=pet).filter(type=dict_weight).order_by('-date', '-created_datetime')
        context['weight_list'] = weight_list[:10]

        return context


class CareCreateView(LoginRequiredMixin, CreateView):
    model = Care
    form_class = CareCreateForm
    template_name = 'pet/care_form.html.j2'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pet = get_object_or_404(Pet, pk=self.kwargs['petid'])
        context['pet'] = pet
        return context

    @transaction.atomic
    def form_valid(self, form):
        # 사육일지유형이 먹이주기 일 때
        if form.cleaned_data['type'].item == reptopia._FEEDING_:
            feeding = Feeding()
            feeding.eat_type = get_object_or_404(Dictionary, pk=form.cleaned_data['eat_type'].id)
            feeding.prey_type = get_object_or_404(Dictionary, pk=form.cleaned_data['prey_type'].id)
            if form.cleaned_data['prey_size'] is not None:
                feeding.prey_size = get_object_or_404(Dictionary, pk=form.cleaned_data['prey_size'].id)
            feeding.prey_weight = form.cleaned_data['prey_weight']
            feeding.prey_quantity = form.cleaned_data['prey_quantity']
            feeding.save()
            form.instance.feeding = feeding

        return super().form_valid(form)


class CareDeleteView(LoginRequiredMixin, DeleteView):
    login_url = settings.LOGIN_URL
    model = Care

    def get_success_url(self):
        pet = self.object.pet
        return reverse_lazy('pet-detail', kwargs={'userid': pet.owner.id, 'pk':pet.id})


class SpeciesSearchTemplateView(View):
    def get(self, request):
        q = request.GET.get('term', '').capitalize()
        logger.debug(q)
        search_qs = AnimalDictionary.objects.filter(Q(common_name_kor__icontains=q)|Q(common_name__icontains=q)|Q(species__icontains=q))

        results  = []
        for r in search_qs:
            value = {}
            value['id'] = r.id
            value['label'] = '[' + r.common_name + '] '+ r.common_name_kor
            results.append(value)
        logger.debug(results)
        data = json.dumps(results)
        mimetype = 'application/json'
        return HttpResponse(data, mimetype)

templates/pet/care_form.html.j2
{% extends 'base.html.j2' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'lib/jquery-ui/css/jquery-ui.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/img-upload.css' %}" />
<style type="text/css">
    .invisible {
        visibility: hidden;
        width: 0px;
        height: 0px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="clearfix">
        <h1 class="float-left">사육일지 등록하기</h1>
    </div>
    <hr>
    <form id="care_form" method="post" action="" class="form-horizontal" enctype="multipart/form-data" data-ajax-url="{% url 'ajax-dict-item-list' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="" />
        <div class="form-group">
            <label for="cname" >{{ form.date.label_tag }}</label>
            <div >
                {% if form.date.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ form.date.errors }}
                    </div>
                {% endif %}
                <div class="input-group">
                    {{ form.date }}
                    <div class="input-group-addon">
                        <span class="glyphicon glyphicon-th"></span>
                    </div>
                    <small class="form-text text-muted">{{ form.date.help_text }}</small>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="cname" >{{ form.type.label_tag }}</label>
            <div >
                {% if form.type.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ form.type.errors }}
                    </div>
                {% endif %}
                {{ form.type }}
                <small class="form-text text-muted">{{ form.type.help_text }}</small>
            </div>
        </div>

        <div class="form-group" id="weight_layer" style="display: none;">
            <label for="cname" >{{ form.weight.label_tag }}</label>
            <div >
                {% if form.weight.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ form.weight.errors }}
                    </div>
                {% endif %}
                {{ form.weight }}
            </div>
        </div>

        <div class="form-group" id="prey_layer" style="display: none;">
            <label for="cname" >{{ form.eat_type.label_tag }}</label>
            <div >
                {% if form.eat_type.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ form.eat_type.errors }}
                    </div>
                {% endif %}
                {{ form.eat_type}}
                {{ form.prey_type }}
                {{ form.prey_size }}
                {{ form.prey_weight }}
                {{ form.prey_quantity }}
            </div>
        </div>

        <div class="form-group">
            <label for="cname" >{{ form.desc.label_tag }}</label>
            <div >
                {% if form.desc.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ form.desc.errors }}
                    </div>
                {% endif %}
                {{ form.desc }}
                <small class="form-text text-muted">{{ form.desc.help_text }}</small>
            </div>
        </div>

        <div class="form-group">
            <label for="cname" >{{ form.image.label_tag }}</label>
            <div >
                {% if form.image.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ form.image.errors }}
                    </div>
                {% endif %}
                <div class="input-group">
                    <span class="input-group-btn">
                        <span class="btn btn-default btn-file">
                            <i class="fa fa-camera-retro"></i>{{ form.image }}
                        </span>
                        <span class="btn btn-default" id="id_file_trash"><i class="fa fa-trash"></i></span>
                    </span>
                    <input type="text" class="form-control" readonly>
                </div>
                <img id='img-upload'/>
                <small class="form-text text-muted">{{ form.image.help_text }}</small>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="btn-group">
                <button id="btn_submit" type="button" class="btn btn-default">등록하기</button>
                <button id="btn_cancle" type="button" class="btn btn-default">돌아가기</button>
            </div>
        </div>

        <div class="invisible">{{ form.pet }}</div>
    </form>
</div>
{% endblock %}

{% block script_content %}
<script src="{% static 'lib/jquery-ui/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'lib/jquery-ui/i18n/datepicker-ko.js' %}"></script>
<script>
    $(document).ready( function() {
        function setAjaxData(item, obj) {
            $.ajax({
                url: $("#care_form").attr("data-ajax-url"),
                data: {
                    'item': item
                },
                success: function (data) {
                    if (data.length > 0) {
                        obj.html(data);
                        obj.attr('disabled',false);
                        obj.attr('readonly', false);
                    } else {
                        obj.attr('disabled',true);
                    }
                }
            });
        }

        $('#{{ form.type.id_for_label}}').change(function(){
            initCareDetail();
            $('#weight_layer').hide()
            $('#prey_layer').hide()
            // 먹이주기
            if ($(this).val() == '2') {
                /*
                setAjaxData('{{ pet.species.eating.id}}', $('#id_prey_type'));
                $('#id_prey_type').change(function() {
                    setAjaxData($(this).val(),$('#id_prey_size'));
                });
                */
                $('#prey_layer').show()
                //$('#{{ form.eat_type.id_for_label }}').val('{{ pet.species.eating.id }}')
            }
            // 체중
            else if ($(this).val() == '6') {
                $('#weight_layer').show()
            }
        });

        $('#{{ form.eat_type.id_for_label }}').change(function() {
            initCareDetail();
            setAjaxData($(this).val(), $('#id_prey_type'));
            $('#id_prey_type').change(function() {
                setAjaxData($(this).val(),$('#id_prey_size'));
            });
        });

        var initCareDetail = function () {
            // 체중초기화
            $('#id_weight').val('');
            // 먹이유형 초기화
            $('#id_prey_type').val('');
            $('#id_prey_type').attr('readonly', true);
            $('#id_prey_size').val('');
            $('#id_prey_size').attr('readonly', true);
            $('#id_prey_weight').val('');
            $('#id_prey_quantity').val('');

        };

        $('#{{ form.pet.id_for_label}}').val('{{ pet.id }}');

        $(document).on('change', '.btn-file :file', function() {
            var input = $(this), label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            input.trigger('fileselect', [label]);
        });

        $('.btn-file :file').on('fileselect', function(event, label) {
            var input = $(this).parents('.input-group').find(':text'), log = label;

            if( input.length ) {
                input.val(log);
            } else {
                if( log ) alert(log);
            }
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#img-upload').attr('src', e.target.result);
                    $('#img-upload').attr('class', 'img-thumbnail');
                }
                reader.readAsDataURL(input.files[0]);
            } else {
                $('#img-upload').attr('src', '');
                $('#img-upload').removeClass('img-thumbnail');
            }
        }

        $("#id_image").change(function(){
            readURL(this);
        });

        $("#id_file_trash").click(function() {
            $("#id_image").val('');
            $('.input-group :text').val('');
            readURL($("#id_image"));
        });

        $("#id_date").datepicker({
            dateFormat: "yy-mm-dd",
            changeMonth: true,
            changeYear: true
        });
        $("#id_date").datepicker($.datepicker.regional[ "ko" ]);

        $('#btn_submit').on('click', function() {
            $( function() {
                $('#dialog-body').text('입력하신 내용으로 사육일지를 등록하시겠습니까?');
                $( "#dialog-message" ).dialog({
                    modal: true,
                    title: "사육일지 등록확인",
                    buttons: {
                        '확인': function() {
                            $( '#care_form' ).submit();
                        },
                        '취소': function() {
                            $( this ).dialog( "close" );
                        }
                    },
                });
            });
        });

        $('#btn_cancle').on('click', function() {
            window.location = "{{ pet.get_absolute_url }}";
        });


        $('#{{ form.type.id_for_label}}').change()
        if ($('#{{ form.eat_type.id_for_label}}').val()) {
            $('#{{ form.eat_type.id_for_label}}').change()
        }
    });
</script>
{% endblock%}