bbs/urls.py
from django.urls import path, include
from . import views as bbs_views

urlpatterns = [
    path('bbs/<bbs_type>/list', bbs_views.PostListView.as_view(), name='board-list'),
    path('bbs/<bbs_type>/add', bbs_views.PostCreateView.as_view(), name='board-add'),
    path('bbs/<bbs_type>/<int:pk>/', bbs_views.PostDetailView.as_view(), name='board-detail'),
    path('bbs/<bbs_type>/<int:pk>/delete', bbs_views.PostDeleteView.as_view(), name='board-delete'),
    path('bbs/<bbs_type>/<int:pk>/update', bbs_views.PostUpdateView.as_view(), name='board-update'),
]

pet/models.py
from django.db import models
from django.conf import settings
from dict.models import Dictionary, AnimalDictionary
from django.utils import timezone
from django.urls import reverse
from django.utils.formats import localize
from taggit.managers import TaggableManager
import reptopia

class Pet(models.Model):
    species = models.ForeignKey(AnimalDictionary, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    gender = models.ForeignKey(
        Dictionary,
        related_name='gender',
        on_delete=models.CASCADE,
        limit_choices_to={'category': reptopia._GENDER_},
    )
    bod = models.DateField(blank=True, null=True)
    image = models.ImageField(upload_to='pet/%Y/%m/%d', blank=True, null=True)
    desc = models.TextField(blank=True)

    created_date = models.DateTimeField(default=timezone.now)

    tags = TaggableManager()

    def __str__(self):
        return '[' + self.species.common_name_kor + ']' + self.name;

    def get_absolute_url(self):
        return reverse('pet-detail', kwargs={'userid': self.owner.pk, 'pk': self.pk})

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.tags.clear()
        super(Pet, self).delete(*args, **kwargs)

    def get_model_name(self):
        return Pet.__name__


class Feeding(models.Model):
    eat_type = models.ForeignKey(
        Dictionary,
        related_name='eat_type',
        on_delete=models.CASCADE,
        default=21
    )
    prey_type = models.ForeignKey(
        Dictionary,
        related_name='prey_type',
        on_delete=models.CASCADE,
    )
    prey_size = models.ForeignKey(
        Dictionary,
        related_name='prey_size',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    prey_weight = models.IntegerField(blank=True, null=True)
    prey_quantity = models.IntegerField(default=1)


class Care(models.Model):
    date = models.DateField(default=timezone.now, blank=False)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    type = models.ForeignKey(
        Dictionary,
        related_name='care_type',
        on_delete=models.CASCADE,
        limit_choices_to={'category': reptopia._CARE_},
    )
    weight = models.IntegerField(null=True)
    feeding = models.ForeignKey(
        Feeding,
        on_delete=models.CASCADE,
        null=True
    )
    image = models.ImageField(upload_to='care/%Y/%m/%d', blank=True, null=True)
    desc = models.TextField(blank=True)
    created_datetime = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.pet.name + " : " + localize(self.date) + " : " + self.type.item

    def delete(self, *args, **kwargs):
        self.image.delete()
        if self.feeding:
            self.feeding.delete()
        super(Care, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pet-detail', kwargs={'userid': self.pet.owner.pk, 'pk': self.pet.pk})

templates/comments/form.html
{% load comments %}
{% get_comment_form for object as form %}
{% if user.is_authenticated %}
<form method="POST" action="/comments/post/"> {% csrf_token %}
    <div class="row mt-5">
        <div class="col-sm-12">
            <div class="alert alert-danger" data-comment-element="errors" hidden> </div>
            {{ form.content_type }}
            {{ form.object_pk }}
            {{ form.timestamp }}
            {{ form.security_hash }}
            <input type="hidden" name="next" value="/comments/sent/"/>
            <input type="hidden" name="name" value="{{user.name}}" id="id_name">
            <input type="hidden" name="reply_to" value="0" id="id_reply_to">
            <input type="hidden" name="honeypot" id="id_honeypot">
            <label for="cname" >{{ user.name }}</label>
            <div class="input-group mb-3">
                <textarea name="comment" placeholder="댓글을 입력해주세요." rows="1" class="form-control" maxlength="1000" required id="id_comment"></textarea>
                <div class="input-group-append">
                    <input type="submit" name="post" value="등록하기" class="btn btn-outline-secondary" />
                </div>
            </div>
        </div>
    </div>
</form>
{% endif %}

templates/comments/list.html
{% load comments %}
{% get_comment_count for object as comment_count %}
{% if comment_count %}
{% get_comment_list for object as comment_list %}
{% for comment in comment_list %}
<div class="row">
    <div class="col-sm-12">
        <div class="mt-3">{{ comment.comment }}</div>
        <small class="text-muted">{{ comment.submit_date }} by {{ comment.user.name }}
        {% if user.is_staff %}
            - <i name="comment_delete" pk="{{ comment.pk }}" class="fa fa-trash"></i>
        {% endif %}
        </small>
    </div>
</div>
{% endfor %}
{% endif %}